require_relative 'pieces/null_piece'
require_relative 'pieces/piece'
require_relative 'pieces/slidable'
require_relative 'pieces/steppable'
require_relative 'pieces/king'
require_relative 'pieces/queen'
require_relative 'pieces/rook'
require_relative 'pieces/bishop'
require_relative 'pieces/knight'
require_relative 'pieces/pawn'

require_relative 'assets/cursorable'
require_relative 'assets/board'
require_relative 'assets/display'
require_relative 'assets/player'
